# Generated by Django 5.2 on 2025-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boekenclub', '0002_book_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
